doctrine:
    dbal:
        driver: pdo_mysql
        host: 'localhost'
        dbname: 'finance'
        user: 'root'
        password: 'root'
        charset: UTF8
        options:
            1002: "SET NAMES 'UTF8' COLLATE 'utf8_general_ci'"
        default_table_options:
            charset: utf8
            collate: utf8_general_ci

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App